# Generated by Django 3.2.5 on 2021-07-16 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import real_estate.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20210620_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(blank=True, max_length=200, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Address 1')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Address 2')),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code')),
                ('city', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='subregion', chained_model_field='subregion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='cities_light.country', verbose_name='Country')),
                ('region', smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
                ('subregion', smart_selects.db_fields.ChainedForeignKey(chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Visible', [('new', 'new'), ('archived', 'archived'), ('active', 'active')]), ('Invisible', [('draft', 'draft'), ('deleted', 'deleted')])], default='draft', max_length=30)),
                ('listing_status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('for_rent', 'For Sale and Rent'), ('rental_under_offer', 'Rental - Under Offer'), ('sale_under_offer', 'Sale - Under Offer'), ('sold', 'Sold'), ('rented', 'Rented')], default='for_sale', max_length=30)),
                ('listing_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('business', 'Business')], default='residential', max_length=20)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('office', 'Office'), ('business', 'Business'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('hospitality', 'Hospitality')], default='house', max_length=20)),
                ('bed_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('bath_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('floors_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('floor_location', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('sq_meters', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('year_built', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0), real_estate.models.max_value_current_year], verbose_name='year')),
                ('land_size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('furnishings', models.CharField(choices=[('fully_furnished', 'Fully Furnished'), ('partly_furnished', 'Partly Furnished'), ('unfurnished', 'Unfurnished'), ('not_applicable', 'N/A')], default='unfurnished', max_length=50)),
                ('parking_spaces', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('reference', models.CharField(max_length=20, null=True)),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.TextField(max_length=50000)),
                ('sale_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price')),
                ('rental_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rental Price (monthly)')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to='real_estate.address')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(verbose_name='Property Image URL')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property_listing')),
            ],
        ),
    ]
