# Generated by Django 3.2.4 on 2021-06-18 17:35

import django.core.validators
from django.db import migrations, models
import model_utils.fields
import real_estate.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_listing',
            name='id',
        ),
        migrations.AddField(
            model_name='property_listing',
            name='bath_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='bed_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='floor_location',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='floors_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='furnishings',
            field=models.CharField(choices=[('fully_furnished', 'Fully Furnished'), ('partly_furnished', 'Partly Furnished'), ('unfurnished', 'Unfurnished'), ('not_applicable', 'N/A')], default='unfurnished', max_length=50),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='land_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='listing_status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('for_rent', 'For Sale and Rent'), ('rental_under_offer', 'Rental - Under Offer'), ('sale_under_offer', 'Sale - Under Offer'), ('sold', 'Sold'), ('rented', 'Rented')], default='for_sale', max_length=30),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='listing_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('business', 'Business')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='parking_spaces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('office', 'Office'), ('business', 'Business'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('hospitality', 'Hospitality')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='reference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='sq_meters',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='status',
            field=models.CharField(choices=[('Visible', [('new', 'new'), ('archived', 'archived'), ('active', 'active')]), ('Invisible', [('draft', 'draft'), ('deleted', 'deleted')])], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='uuid',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='year_built',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0), real_estate.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
