# Generated by Django 3.2.4 on 2021-06-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_listing',
            name='country',
        ),
        migrations.CreateModel(
            name='TownCityRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_city_region', to='real_estate.country')),
            ],
        ),
    ]
