# Generated by Django 3.2.4 on 2021-06-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20210620_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TownCityRegion',
        ),
    ]
