# Generated by Django 3.2.4 on 2021-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20210618_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='full_description',
            field=models.TextField(default='This property does not have a description', max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='short_description',
            field=models.CharField(default='No short desctiption available', max_length=500),
            preserve_default=False,
        ),
    ]
