# Generated by Django 3.2.7 on 2021-10-04 14:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0004_district_subdistrict'),
        ('real_estate', '0003_auto_20211003_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='globe.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='province', chained_model_field='province', default='', on_delete=django.db.models.deletion.CASCADE, to='globe.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', default='', on_delete=django.db.models.deletion.CASCADE, to='globe.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='subdistrict',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='district', chained_model_field='district', default='', on_delete=django.db.models.deletion.CASCADE, to='globe.subdistrict'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
