# Generated by Django 3.2.4 on 2021-06-19 12:44

from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_auto_20210618_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='uuid',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
    ]
