# Generated by Django 3.2.4 on 2021-06-19 12:48

from django.db import migrations
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_auto_20210619_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='uuid',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
    ]
