# Generated by Django 3.2.7 on 2021-10-04 14:38

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0004_district_subdistrict'),
        ('real_estate', '0004_auto_20211004_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='adm0_pcode', on_delete=django.db.models.deletion.CASCADE, to='globe.province'),
        ),
    ]
