# Generated by Django 3.2.7 on 2021-10-04 14:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0004_district_subdistrict'),
        ('real_estate', '0005_alter_address_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='province', chained_model_field='adm1_pcode', on_delete=django.db.models.deletion.CASCADE, to='globe.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='subdistrict',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='district', chained_model_field='adm2_pcode', on_delete=django.db.models.deletion.CASCADE, to='globe.subdistrict'),
        ),
    ]
