# Generated by Django 3.2.4 on 2021-06-21 20:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210620_1848'),
        ('real_estate', '0005_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='subregion', chained_model_field='subregion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
