# Generated by Django 3.2.4 on 2021-06-19 12:49

from django.db import migrations
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_alter_property_listing_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='uuid',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
    ]
