# Generated by Django 3.2.7 on 2021-10-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0004_district_subdistrict'),
        ('real_estate', '0006_auto_20211004_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default='TH', on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='globe.country', verbose_name='Country'),
        ),
    ]
