# Generated by Django 3.2.4 on 2021-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Address 1'),
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Address 2'),
        ),
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='locale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code'),
        ),
    ]
