# Generated by Django 3.2.4 on 2021-06-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_auto_20210621_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to='real_estate.address'),
            preserve_default=False,
        ),
    ]
