# Generated by Django 3.2.4 on 2021-06-21 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210620_1848'),
        ('real_estate', '0008_property_listing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='rental_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rental Price (monthly)'),
        ),
        migrations.AddField(
            model_name='property_listing',
            name='sale_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='cities_light.country', verbose_name='Country'),
        ),
    ]
