# Generated by Django 3.2.4 on 2021-06-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_auto_20210621_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
