# Generated by Django 3.2.4 on 2021-06-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210620_1848'),
        ('real_estate', '0010_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='cities_light.country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
