# Generated by Django 3.2.7 on 2021-10-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_auto_20211004_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='address',
            name='poi_lat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='poi_lng',
        ),
    ]
