# Generated by Django 3.2.7 on 2021-10-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0006_alter_poi_loc'),
        ('real_estate', '0014_address_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='globe.poi'),
        ),
    ]
