# Generated by Django 3.2.7 on 2021-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_alter_address_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='listing_status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('for_sale_rent', 'For Sale and Rent'), ('rental_under_offer', 'Rental - Under Offer'), ('sale_under_offer', 'Sale - Under Offer'), ('sold', 'Sold'), ('rented', 'Rented')], default='for_sale', max_length=30),
        ),
    ]
