# Generated by Django 3.2.7 on 2021-10-07 02:25

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='globe.country')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='globe.country')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm3_en', models.CharField(max_length=50)),
                ('adm3_th', models.CharField(max_length=50)),
                ('adm3_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.country')),
                ('adm1_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.province')),
                ('adm2_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.district')),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('loc', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(100.52974993962351, 13.741090616723785), geography=True, srid=4326)),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='globe.subdistrict')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='adm1_pcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='globe.province'),
        ),
    ]
