# Generated by Django 3.2.7 on 2021-10-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='adm0_pcode',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
