# Generated by Django 3.2.7 on 2021-10-01 17:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globe', '0002_auto_20211001_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='globe.country')),
            ],
        ),
    ]
