# Generated by Django 3.2.7 on 2021-10-01 19:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0003_country_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='globe.country')),
                ('adm1_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='globe.province')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm3_en', models.CharField(max_length=50)),
                ('adm3_th', models.CharField(max_length=50)),
                ('adm3_pcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adm0_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.country')),
                ('adm1_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.province')),
                ('adm2_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='globe.district')),
            ],
        ),
    ]
