# Generated by Django 3.2.7 on 2021-10-04 22:50

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0005_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), dim=models.FloatField(), srid=4326, verbose_name=models.FloatField()),
        ),
    ]
