# Generated by Django 3.2.7 on 2021-10-04 22:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0006_alter_poi_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poi',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poi',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), dim=models.DecimalField(decimal_places=6, max_digits=10), srid=4326, verbose_name=models.DecimalField(decimal_places=6, max_digits=10)),
        ),
    ]
