# Generated by Django 3.2.7 on 2021-10-04 22:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0007_auto_20211004_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
