# Generated by Django 3.2.7 on 2021-10-04 23:01

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0010_alter_poi_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(100.52974993962351, 13.741090616723785), geography=True, srid=4326),
        ),
    ]
