# Generated by Django 3.2.7 on 2021-10-07 02:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm3_en', models.CharField(max_length=50)),
                ('adm3_th', models.CharField(max_length=50)),
                ('adm3_pcode', models.CharField(max_length=50)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='thailandPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_th', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_th', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_th', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm3_en', models.CharField(max_length=50)),
                ('adm3_th', models.CharField(max_length=50)),
                ('adm3_pcode', models.CharField(max_length=50)),
                ('adm3_ref', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adm3alt1en', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adm3alt2en', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adm3alt1th', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('adm3alt2th', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='thailandShapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('admlevel', models.IntegerField()),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('validto', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
