# Generated by Django 3.2.5 on 2021-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thailand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thailandplaces',
            name='adm3_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
