# Generated by Django 3.2.5 on 2021-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thailand', '0002_alter_thailandplaces_adm3_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thailandplaces',
            name='adm3_ref',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
