# Generated by Django 3.2.5 on 2021-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thailand', '0006_auto_20210929_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='validto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
