# Generated by Django 3.2.5 on 2021-09-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thailand', '0009_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='adm0_ref',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adm0alt1en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adm0alt1th',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adm0alt2en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adm0alt2th',
        ),
        migrations.RemoveField(
            model_name='country',
            name='validto',
        ),
    ]
