# Generated by Django 3.2.5 on 2021-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='geom',
        ),
    ]
