# Generated by Django 3.1.13 on 2021-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_worldborder_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
