# Generated by Django 3.2.7 on 2021-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20211003_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
